[package]
name        = "bibblitz"
description = "test"
version     = "1.0.0"
flix        = "0.65.0"
authors     = ["Magnus Madsen"]

[dependencies]
"github:mlutze/flix-json" = { version = "0.13.1", security = "unrestricted" }

